name: Flip API Tests

on:
  push:
    branches:
      - main

jobs:
  run-chai-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: ./automation-chai

      - name: Run Chai/Mocha tests
        run: npm test
        working-directory: ./automation-chai