name: Flip Web Tests

on:
  push:
    branches:
      - main

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: ./automation-cypress

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./automation-cypress
